import Head from "next/head";
import styles from "../styles/Home.module.css";

const minutesAgo = (date) => {
  var diff = Math.abs(new Date(date) - Date.now());
  return Math.floor(diff / 1000 / 60);
};

const TuitahTimeline = ({ tuits }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Tuitah Next</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.description}>Tuitah Timeline</h1>
        <ul>
          {tuits.reverse().map((tuit) => (
            <>
              <li key={tuit._id}>
                <p>{tuit.text}</p>
                <p>{`${minutesAgo(tuit.date)} minutes ago`}</p>
                <p>{`Likes ${tuit.likes}`}</p>
              </li>
            </>
          ))}
        </ul>
      </main>

      <footer className={styles.footer}>
        <p>Powered by David S & Berenguer P</p>
      </footer>
    </div>
  );
};

export const getServerSideProps = async () => {
  const response = await fetch(process.env.NEXT_TUITAH_API_URL);
  const { tuits } = await response.json();
  console.log(tuits);
  return {
    props: { tuits },
  };
};

export default TuitahTimeline;
